#!/usr/bin/env python3
"""
run_all.py
A wrapper script to execute Phase 1 (packet_factory.py) and Phase 2 (main.py)
sequentially on a single PCAP file.

Usage:
  python3 run_all.py path/to/capture.pcap
"""

import os
import sys
import subprocess
from pathlib import Path

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 run_all.py <pcap_file>")
        sys.exit(1)
        
    pcap_path = Path(sys.argv[1]).resolve()
    
    if not pcap_path.exists():
        print(f"Error: PCAP file not found at {pcap_path}")
        sys.exit(1)
        
    stem = pcap_path.stem

    print(f"============================================================")
    print(f" PHASE 1: Extracting and building Data Lake for {stem}")
    print(f"============================================================")
    
    try:
        subprocess.run([sys.executable, "packet_factory.py", str(pcap_path)], check=True)
    except subprocess.CalledProcessError:
        print("\n❌ Phase 1 failed! Aborting.")
        sys.exit(1)
        
    print(f"\n============================================================")
    print(f" PHASE 2: Enriching and processing IOCs for {stem}")
    print(f"============================================================")
    
    # We pass the expected processed directory to main.py so it explicitly
    # targets the output generated by Phase 1, avoiding any auto-detect confusion.
    processed_target = f"processed/{stem}"
    
    try:
        subprocess.run([sys.executable, "ioc_extractor.py", processed_target], check=True)
    except subprocess.CalledProcessError:
        print("\n❌ Phase 2 failed!")
        sys.exit(1)
        
    print(f"\n============================================================")
    print(f" PHASE 3: Correlation & Attack Chain Scoring for {stem}")
    print(f"============================================================")
    
    # Phase 2 creates an output folder like 'phase2_output/Hive_20260428_120000/'
    # We need to find the most recent one for this stem.
    phase2_base = Path("phase2_output")
    matching_dirs = sorted(
        [d for d in phase2_base.iterdir() if d.is_dir() and d.name.startswith(stem + "_")],
        key=os.path.getmtime,
        reverse=True
    )
    
    if matching_dirs:
        latest_phase2 = matching_dirs[0]
        try:
            subprocess.run([sys.executable, "correlation.py", processed_target, str(latest_phase2)], check=True)
        except subprocess.CalledProcessError:
            print("\n❌ Phase 3 failed!")
            sys.exit(1)
    else:
        print(f"⚠️ Could not locate Phase 2 output directory for {stem} to run Phase 3.")
        
    print("\n✅ Complete Pipeline Finished Successfully!")

if __name__ == "__main__":
    main()
